# ==============================================================
# APAF Bioinformatics | HydraR | test-vignette_logic.R
# Purpose:     Verifies the core logic used in vignettes.
# ==============================================================

test_that("Sorting Benchmark logic is sound", {
  # Mock the sorting logic that would be generated by agents
  bubble_sort <- function(x) {
    n <- length(x)
    for (i in 1:(n - 1)) {
      for (j in 1:(n - i)) {
        if (x[j] > x[j + 1]) {
          temp <- x[j]
          x[j] <- x[j + 1]
          x[j + 1] <- temp
        }
      }
    }
    return(x)
  }
  
  input <- c(5, 2, 8, 1, 9)
  expect_equal(bubble_sort(input), sort(input))
})

test_that("Hong Kong Travel DAG can be spawned from manifest", {
  # Use the actual vignette YAML if available
  # We use a mock if not to keep test fast
  manifest <- list(
    graph = "graph TD\n  A[Planner] --> B[Validator]",
    initial_state = list(destination = "Hong Kong")
  )
  
  dag <- spawn_dag(manifest, auto_node_factory())
  expect_s3_class(dag, "AgentDAG")
  expect_true("A" %in% names(dag$nodes))
})

test_that("State Persistence logic handles pause/resume", {
  dag <- AgentDAG$new()
  dag$add_node(AgentLogicNode$new(id = "Step1", function(state) {
    state$set("val", 1)
    return(list(status = "NEXT"))
  }))
  dag$add_node(AgentLogicNode$new(id = "Step2", function(state) {
    if (!state$get("fixed", default = FALSE)) return(list(status = "PAUSE"))
    state$set("val", 2)
    return(list(status = "SUCCESS"))
  }))
  dag$add_edge("Step1", "Step2")
  
  # Run 1: Should pause
  res1 <- dag$run(initial_state = list(fixed = FALSE))
  expect_equal(res1$status, "completed") # Engine status is completed even if paused internally
  
  # Run 2: Resume
  res2 <- dag$run(initial_state = list(fixed = TRUE), resume_from = "Step2")
  expect_equal(res2$status, "completed")
  expect_equal(res2$state$get("val"), 2)
})
